import 'dart:convert';

import 'package:protobuf/protobuf.dart';
import 'package:protod/delta/delta.dart' as delta;
import 'package:protod/delta/delta_transform.dart';
import 'package:test/test.dart';

import 'pb/registry.dart' as registry;
import 'pb/tests.pb.dart';

void main() {
  delta.setDefaultRegistry(registry.types);
  final cases = CASES.split("\n").map((str) {
    var a = TransformTestCase();
    a.mergeFromProto3Json(jsonDecode(str), typeRegistry: registry.types);
    return a;
  });
  final solo = cases.any((info) => info.solo ?? false);
  cases.forEach((TransformTestCase info) {
    if (solo && !(info.solo ?? false)) {
      return;
    }
    test(info.name, () {
      var data = delta.unpack(info.data);

      final op2xp1 = transform(info.op1, info.op2, true);
      final op2xp2 = transform(info.op1, info.op2, false);
      final op1xp2 = transform(info.op2, info.op1, true);
      final op1xp1 = transform(info.op2, info.op1, false);

      var data1p1 = data.clone();
      var data1p2 = data.clone();
      var data2p1 = data.clone();
      var data2p2 = data.clone();

      delta.apply(info.op1, data1p1);
      delta.apply(op2xp1, data1p1);

      delta.apply(info.op1, data1p2);
      delta.apply(op2xp2, data1p2);

      delta.apply(info.op2, data2p1);
      delta.apply(op1xp1, data2p1);

      delta.apply(info.op2, data2p2);
      delta.apply(op1xp2, data2p2);

      expect(toObject(data1p1), toObject(data2p1),
          reason: "data1p1 != data2p1");
      expect(toObject(data1p2), toObject(data2p2),
          reason: "data1p2 != data2p2");

      if (info.hasExpected()) {
        var expected = delta.unpack(info.expected);
        expect(
          toObject(data1p1),
          toObject(expected),
          reason: "data1p1 != expected",
        );
        expect(
          toObject(data1p2),
          toObject(expected),
          reason: "data1p2 != expected",
        );
      } else {
        var expected1 = delta.unpack(info.expected1);
        var expected2 = delta.unpack(info.expected2);
        expect(
          toObject(data1p1),
          toObject(expected1),
          reason: "data1p1 != expected1",
        );
        expect(
          toObject(data1p2),
          toObject(expected2),
          reason: "data1p2 != expected2",
        );
      }
    });
  });
}

Object toObject(GeneratedMessage msg) {
  var ob = msg.toProto3Json(typeRegistry: registry.types);
  return process(ob);
}

Object process(Object o) {
  if (o is Map) {
    Map out = {};
    o.forEach((key, value) {
      final child = process(value);
      if (child != null) {
        out[key] = child;
      }
    });
    if (out.length == 0) {
      return null;
    }
    return out;
  } else if (o is List) {
    List out = [];
    o.forEach((element) {
      final child = process(element);
      if (child != null) {
        out.add(child);
      }
    });
    if (out.length == 0) {
      return null;
    }
    return out;
  }
  return o;
}

const CASES =
    '''{"name":"renames_bug","op1":{"type":"Rename","location":[{"field":{"name":"cases","number":4}},{"key":{"string":"a"}}],"key":{"string":"b"}},"op2":{"type":"Rename","location":[{"field":{"name":"cases","number":4}},{"key":{"string":"a"}},{"field":{"name":"flags","number":23}},{"key":{"int64":"1"}}],"key":{"int64":"3"}},"data":{"@type":"type.googleapis.com/tests.Person","cases":{"a":{"name":"b","flags":{"1":"c"}}}},"expected":{"@type":"type.googleapis.com/tests.Person","cases":{"b":{"name":"b","flags":{"3":"c"}}}}}
{"name":"renames","op1":{"type":"Rename","location":[{"field":{"name":"cases","number":4}},{"key":{"string":"a"}}],"key":{"string":"b"}},"op2":{"type":"Rename","location":[{"field":{"name":"cases","number":4}},{"key":{"string":"a"}}],"key":{"string":"c"}},"data":{"@type":"type.googleapis.com/tests.Person","cases":{"a":{"name":"x"}}},"expected1":{"@type":"type.googleapis.com/tests.Person","cases":{"b":{"name":"x"}}},"expected2":{"@type":"type.googleapis.com/tests.Person","cases":{"c":{"name":"x"}}}}
{"name":"delete_key_edit_inside", "op1":{"type":"Edit", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"b"}}, {"field":{"name":"name", "number":21}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"d"}]}}}, "op2":{"type":"Delete", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"b"}}]}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a", "cases":{"b":{"name":"c"}}}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"a"}}
{"name":"index_shifter_ancestor", "op1":{"type":"Set", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"a"}}, {"field":{"name":"items", "number":22}}, {"index":"1"}, {"field":{"name":"done", "number":34}}], "scalar":{"bool":true}}, "op2":{"type":"Delete", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"a"}}, {"field":{"name":"items", "number":22}}, {"index":"2"}]}, "data":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"items":[{"title":"a"}, {"title":"b"}, {"title":"c"}]}}}, "expected":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"items":[{"title":"a"}, {"title":"b", "done":true}]}}}}
{"name":"compound", "op1":{"type":"Compound", "ops":[{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"a"}}, {"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"b"}]}}}]}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"c"}}, "data":{"@type":"type.googleapis.com/tests.Person"}, "expected1":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "c"]}, "expected2":{"@type":"type.googleapis.com/tests.Person", "alias":["c", "b"]}}
{"name":"compound_2", "op1":{"type":"Compound", "ops":[{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"a"}}, {"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"b"}]}}}]}, "op2":{"type":"Compound", "ops":[{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"c"}}, {"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"d"}]}}}]}, "data":{"@type":"type.googleapis.com/tests.Person"}, "expected1":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "d"]}, "expected2":{"@type":"type.googleapis.com/tests.Person", "alias":["d", "b"]}}
{"name":"compound_3", "op1":{"type":"Compound", "ops":[{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"a"}}, {"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"b"}]}}}, {"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"c"}}, {"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"d"}]}}}]}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"e"}}, "data":{"@type":"type.googleapis.com/tests.Person"}, "expected1":{"@type":"type.googleapis.com/tests.Person", "alias":["d", "b", "e"]}, "expected2":{"@type":"type.googleapis.com/tests.Person", "alias":["e", "d", "b"]}}
{"name":"oneof_insert_set", "op1":{"type":"Insert", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"itm", "number":3}}, {"field":{"name":"flags", "number":35}}, {"index":"1"}], "scalar":{"string":"b"}}, "op2":{"type":"Set", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"dbl", "number":2}}], "scalar":{"double":1}}, "data":{"@type":"type.googleapis.com/tests.Chooser", "itm":{"flags":["a"]}}, "expected1":{"@type":"type.googleapis.com/tests.Chooser", "itm":{"flags":["b"]}}, "expected2":{"@type":"type.googleapis.com/tests.Chooser", "dbl":1}}
{"name":"set_inner_delete", "op1":{"type":"Set", "location":[{"field":{"name":"company", "number":5}}, {"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "scalar":{"string":"b"}}, "op2":{"type":"Delete", "location":[{"field":{"name":"company", "number":5}}]}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a", "company":{"name":"a", "flags":{"1":"a"}}}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"a"}}
{"name":"oneof_move_set", "op1":{"type":"Move", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"itm", "number":3}}, {"field":{"name":"flags", "number":35}}, {"index":"0"}], "index":"3"}, "op2":{"type":"Set", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"dbl", "number":2}}], "scalar":{"double":1}}, "data":{"@type":"type.googleapis.com/tests.Chooser", "itm":{"flags":["a", "b", "c"]}}, "expected1":{"@type":"type.googleapis.com/tests.Chooser", "dbl":1}, "expected2":{"@type":"type.googleapis.com/tests.Chooser", "dbl":1}}
{"name":"oneof_set_inner_set", "op1":{"type":"Set", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"itm", "number":3}}, {"field":{"name":"title", "number":31}}], "scalar":{"string":"b"}}, "op2":{"type":"Set", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"dbl", "number":2}}], "scalar":{"double":1}}, "data":{"@type":"type.googleapis.com/tests.Chooser", "itm":{"title":"a", "done":true}}, "expected1":{"@type":"type.googleapis.com/tests.Chooser", "itm":{"title":"b"}}, "expected2":{"@type":"type.googleapis.com/tests.Chooser", "dbl":1}}
{"name":"oneof_edit_set", "op1":{"type":"Edit", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"itm", "number":3}}, {"field":{"name":"title", "number":31}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"b"}]}}}, "op2":{"type":"Set", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"dbl", "number":2}}], "scalar":{"double":1}}, "data":{"@type":"type.googleapis.com/tests.Chooser", "itm":{"title":"a", "done":true}}, "expected1":{"@type":"type.googleapis.com/tests.Chooser", "dbl":1}, "expected2":{"@type":"type.googleapis.com/tests.Chooser", "dbl":1}}
{"name":"oneof_set_set", "op1":{"type":"Set", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"dbl", "number":2}}], "scalar":{"double":2}}, "op2":{"type":"Set", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"str", "number":1}}], "scalar":{"string":"a"}}, "data":{"@type":"type.googleapis.com/tests.Chooser"}, "expected1":{"@type":"type.googleapis.com/tests.Chooser", "dbl":2}, "expected2":{"@type":"type.googleapis.com/tests.Chooser", "str":"a"}}
{"name":"delete_all_insert", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"b"}}, "op2":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}]}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a"]}, "expected":{"@type":"type.googleapis.com/tests.Person"}}
{"name":"delete_field_delete_field_independent", "op1":{"type":"Delete", "location":[{"field":{"name":"name", "number":1}}]}, "op2":{"type":"Delete", "location":[{"field":{"name":"age", "number":2}}]}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a", "age":10, "alias":["b", "c"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "c"]}}
{"name":"delete_field_delete_field", "op1":{"type":"Delete", "location":[{"field":{"name":"name", "number":1}}]}, "op2":{"type":"Delete", "location":[{"field":{"name":"name", "number":1}}]}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a", "age":10, "alias":["b", "c"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "age":10, "alias":["b", "c"]}}
{"name":"move_move_not_bug", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "index":"6"}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"3"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e", "f"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "d", "e", "f", "c"]}}
{"name":"move_index_insert_index_backward_4", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "index":"1"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"4"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "d", "b", "c", "x"]}}
{"name":"move_index_insert_index_backward_3", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "index":"1"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "d", "b", "c", "x"]}}
{"name":"move_index_insert_index_backward_2", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "index":"1"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "d", "b", "x", "c"]}}
{"name":"move_index_insert_index_backward_1", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "index":"1"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected1":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "d", "x", "b", "c"]}, "expected2":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "x", "d", "b", "c"]}}
{"name":"move_index_insert_index_backward_0", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "index":"1"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "a", "d", "b", "c"]}}
{"name":"move_index_insert_index_forward_4", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"4"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"4"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected1":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "c", "d", "b", "x"]}, "expected2":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "c", "d", "x", "b"]}}
{"name":"move_index_insert_index_forward_3", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"4"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "c", "x", "d", "b"]}}
{"name":"move_index_insert_index_forward_2", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"4"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "x", "c", "d", "b"]}}
{"name":"move_index_insert_index_forward_1", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"4"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "x", "c", "d", "b"]}}
{"name":"move_index_insert_index_forward_0", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"4"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "a", "c", "d", "b"]}}
{"name":"move_index_insert_index_to", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"4"}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "c", "x", "d", "b"]}}
{"name":"insert_index_move_index_from", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"4"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "x", "c", "d", "b"]}}
{"name":"insert_index_move_index_independent_end_reverse", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "index":"1"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "c", "b", "x", "d"]}}
{"name":"insert_index_move_index_independent_mid_reverse", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "index":"1"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "d", "b", "x", "c"]}}
{"name":"insert_index_move_index_independent_before_reverse", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "index":"1"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "a", "c", "b", "d"]}}
{"name":"insert_index_move_index_independent_end_forward", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"3"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected1":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "c", "x", "b", "d"]}, "expected2":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "c", "b", "x", "d"]}}
{"name":"insert_index_move_index_independent_mid_forward", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"4"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "x", "c", "d", "b"]}}
{"name":"insert_index_move_index_independent_before_forward", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"3"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "a", "c", "b", "d"]}}
{"name":"insert_index_move_index_null", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"0"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "a", "b", "c", "d"]}}
{"name":"set_key_rename_key_to", "op1":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "scalar":{"string":"x"}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "key":{"int64":"2"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected1":{"@type":"type.googleapis.com/tests.Company", "flags":{"2":"x"}}, "expected2":{"@type":"type.googleapis.com/tests.Company", "flags":{"2":"a"}}}
{"name":"set_key_rename_key_from", "op1":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"x"}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "key":{"int64":"10"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"2":"b", "10":"x"}}}
{"name":"set_key_rename_key_independent_ancestor", "op1":{"type":"Set", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"a"}}, {"field":{"name":"flags", "number":23}}, {"key":{"int64":"1"}}], "scalar":{"string":"x"}}, "op2":{"type":"Rename", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"a"}}], "key":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"flags":{"1":"a"}}}}, "expected":{"@type":"type.googleapis.com/tests.Person", "cases":{"y":{"flags":{"1":"x"}}}}}
{"name":"set_key_rename_key_independent", "op1":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"x"}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "key":{"int64":"10"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"x", "10":"b"}}}
{"name":"set_key_rename_key_null", "op1":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"x"}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "key":{"int64":"1"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"x", "2":"b"}}}
{"name":"replace_index_move_index_independent", "op1":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"3"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "c", "a"]}}
{"name":"replace_index_move_index_to", "op1":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"2"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "a"]}}
{"name":"replace_index_move_index_from", "op1":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"2"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "x"]}}
{"name":"replace_index_null_move_index_from", "op1":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"1"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "b"]}}
{"name":"replace_index_replace_index", "op1":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected1":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "b"]}, "expected2":{"@type":"type.googleapis.com/tests.Person", "alias":["y", "b"]}}
{"name":"replace_field_delete_field", "op1":{"type":"Set", "location":[{"field":{"name":"name", "number":11}}], "scalar":{"string":"b"}}, "op2":{"type":"Delete", "location":[{"field":{"name":"name", "number":11}}]}, "data":{"@type":"type.googleapis.com/tests.Company", "name":"a"}, "expected1":{"@type":"type.googleapis.com/tests.Company", "name":"b"}, "expected2":{"@type":"type.googleapis.com/tests.Company"}}
{"name":"edit_key_delete_key", "op1":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Delete", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}]}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"2":"b"}}}
{"name":"edit_key_move_key_null", "op1":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "key":{"int64":"1"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"x", "2":"b"}}}
{"name":"edit_key_move_key_independent", "op1":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "key":{"int64":"3"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"x", "3":"b"}}}
{"name":"edit_key_move_key_to", "op1":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "key":{"int64":"2"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"2":"a"}}}
{"name":"edit_key_move_key_from", "op1":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "key":{"int64":"2"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"2":"x"}}}
{"name":"edit_key_insert_key", "op1":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"y", "2":"b"}}}
{"name":"edit_key_replace_key_independent", "op1":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"x", "2":"y"}}}
{"name":"edit_key_replace_key", "op1":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"y", "2":"b"}}}
{"name":"edit_key_edit_key_independent", "op1":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"y"}]}}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"x", "2":"y"}}}
{"name":"edit_key_edit_key", "op1":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"y"}]}}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected1":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"xy", "2":"b"}}, "expected2":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"yx", "2":"b"}}}
{"name":"edit_index_delete_index", "op1":{"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}]}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b"]}}
{"name":"edit_index_move_index_null", "op1":{"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"0"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "b"]}}
{"name":"edit_index_replace_index", "op1":{"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["y", "b"]}}
{"name":"edit_index_edit_index_independent", "op1":{"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"y"}]}}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "y"]}}
{"name":"edit_index_edit_index", "op1":{"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"y"}]}}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected1":{"@type":"type.googleapis.com/tests.Person", "alias":["xy", "b"]}, "expected2":{"@type":"type.googleapis.com/tests.Person", "alias":["yx", "b"]}}
{"name":"edit_field_delete_field", "op1":{"type":"Edit", "location":[{"field":{"name":"name", "number":1}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"b"}]}}}, "op2":{"type":"Delete", "location":[{"field":{"name":"name", "number":1}}]}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a"}, "expected":{"@type":"type.googleapis.com/tests.Person"}}
{"name":"edit_index_move_index", "op1":{"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"2"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "x"]}}
{"name":"edit_index_insert_index", "op1":{"type":"Edit", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"b"}]}}}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "b"]}}
{"name":"independent_operations_in_same_list", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"4"}], "index":"0"}, "op2":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "index":"4"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["e", "a", "c", "d", "b"]}}
{"name":"ancestor_of_deleted_value", "op1":{"type":"Set", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"a"}}, {"field":{"name":"name", "number":21}}], "scalar":{"string":"x"}}, "op2":{"type":"Rename", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"b"}}], "key":{"string":"a"}}, "data":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"a"}, "b":{"name":"b"}}}, "expected":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"b"}}}}
{"name":"edit_delta_edit_equal", "op1":{"type":"Edit", "location":[{"field":{"name":"name", "number":11}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Set", "location":[{"field":{"name":"name", "number":11}}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Company", "name":"a"}, "expected":{"@type":"type.googleapis.com/tests.Company", "name":"y"}}
{"name":"edit_delta_edit_independent", "op1":{"type":"Edit", "location":[{"field":{"name":"name", "number":11}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"x"}]}}}, "op2":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Company", "name":"a", "flags":{"1":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "name":"x", "flags":{"1":"y"}}}
{"name":"edit_edit_independent", "op1":{"type":"Set", "location":[{"field":{"name":"name", "number":11}}], "scalar":{"string":"x"}}, "op2":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Company", "name":"a", "flags":{"1":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "name":"x", "flags":{"1":"y"}}}
{"name":"edit_insert_key_ancestor", "op1":{"type":"Set", "message":{"@type":"type.googleapis.com/tests.Company", "flags":{"10":"x"}}}, "op2":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "scalar":{"string":"b"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"10":"x"}}}
{"name":"edit_insert_key", "op1":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"x"}}, "op2":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"x", "2":"y"}}}
{"name":"insert_key_edit_equal", "op1":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"y"}}, "op2":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a"}}, "expected1":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"y"}}, "expected2":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"x"}}}
{"name":"edit_insert_index_descendent", "op1":{"type":"Set", "location":[{"field":{"name":"items", "number":22}}], "object":{"list":{"list":[{"message":{"@type":"type.googleapis.com/tests.Item", "title":"x"}}]}}}, "op2":{"type":"Insert", "location":[{"field":{"name":"items", "number":22}}, {"index":"0"}, {"field":{"name":"flags", "number":35}}, {"index":"0"}], "scalar":{"string":"a"}}, "data":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"a"}]}, "expected":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"x"}]}}
{"name":"edit_insert_index_ancestor", "op1":{"type":"Set", "location":[{"field":{"name":"items", "number":22}}], "object":{"list":{"list":[{"message":{"@type":"type.googleapis.com/tests.Item", "title":"x"}}]}}}, "op2":{"type":"Insert", "location":[{"field":{"name":"items", "number":22}}, {"index":"1"}], "message":{"@type":"type.googleapis.com/tests.Item", "title":"b"}}, "data":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"a"}]}, "expected":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"x"}]}}
{"name":"edit_insert_index_after", "op1":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"c"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "c", "b"]}}
{"name":"edit_insert_index_before", "op1":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"x"}}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"c"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["c", "a", "x"]}}
{"name":"edit_insert_index_equal", "op1":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"b"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "x"]}}
{"name":"edit_insert_conflict", "op1":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"b"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "x"]}}
{"name":"edit_insert", "op1":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}], "object":{"list":{"list":[{"scalar":{"string":"x"}}]}}}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"d"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x"]}}
{"name":"move_edit_1", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"2"}, "op2":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}]}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "c"]}}
{"name":"move_edit_2", "op1":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "key":{"int64":"1"}}, "op2":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"c"}]}}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"b"}}}
{"name":"chained_move_1", "op1":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "key":{"int64":"2"}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "key":{"int64":"3"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"3":"a"}}}
{"name":"chained_move_1_reversed", "op1":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "key":{"int64":"3"}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "key":{"int64":"2"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"3":"a"}}}
{"name":"chained_move_1a", "op1":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "key":{"int64":"2"}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "key":{"int64":"3"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b", "3":"c"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"3":"a"}}}
{"name":"chained_move_3", "op1":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "key":{"int64":"1"}}, "op2":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "key":{"int64":"2"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company"}}
{"name":"conflicting_map_move_and_edit", "op1":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "key":{"int64":"3"}}, "op2":{"type":"Edit", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "delta":{"quill":{"ops":[{"delete":"1"}, {"insert":"c"}]}}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "3":"c"}}}
{"name":"conflicting_map_insert_and_delete_1", "op1":{"type":"Delete", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"3"}}]}, "op2":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"3"}}], "scalar":{"string":"c"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected1":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected2":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b", "3":"c"}}}
{"name":"conflicting_deletes", "op1":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}]}, "op2":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}]}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "c"]}}
{"name":"two_deletes", "op1":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}]}, "op2":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}]}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["c"]}}
{"name":"delete_move", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"1"}, "op2":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}]}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "c"]}}
{"name":"conflicting_replace", "op1":{"type":"Set", "location":[{"field":{"name":"company", "number":5}}], "message":{"@type":"type.googleapis.com/tests.Company", "name":"bar"}}, "op2":{"type":"Set", "location":[{"field":{"name":"company", "number":5}}], "message":{"@type":"type.googleapis.com/tests.Company", "name":"baz"}}, "data":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"foo"}}, "expected1":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"bar"}}, "expected2":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"baz"}}}
{"name":"operation_inside_replace_1", "op1":{"type":"Set", "location":[{"field":{"name":"company", "number":5}}], "message":{"@type":"type.googleapis.com/tests.Company", "name":"bar"}}, "op2":{"type":"Set", "location":[{"field":{"name":"company", "number":5}}, {"field":{"name":"name", "number":11}}], "scalar":{"string":"baz"}}, "data":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"foo"}}, "expected":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"bar"}}}
{"name":"operation_inside_replace_2", "op1":{"type":"Set", "location":[{"field":{"name":"company", "number":5}}, {"field":{"name":"name", "number":11}}], "scalar":{"string":"baz"}}, "op2":{"type":"Set", "location":[{"field":{"name":"company", "number":5}}], "message":{"@type":"type.googleapis.com/tests.Company", "name":"bar"}}, "data":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"foo"}}, "expected":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"bar"}}}
{"name":"conflicting_diffs", "op1":{"type":"Edit", "location":[{"field":{"name":"name", "number":1}}], "delta":{"quill":{"ops":[{"retain":"7"}, {"insert":" baz"}]}}}, "op2":{"type":"Edit", "location":[{"field":{"name":"name", "number":1}}], "delta":{"quill":{"ops":[{"retain":"7"}, {"insert":" qux"}]}}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"foo bar"}, "expected1":{"@type":"type.googleapis.com/tests.Person", "name":"foo bar baz qux"}, "expected2":{"@type":"type.googleapis.com/tests.Person", "name":"foo bar qux baz"}}
{"name":"transform_diffs", "op1":{"type":"Edit", "location":[{"field":{"name":"name", "number":1}}], "delta":{"quill":{"ops":[{"retain":"7"}, {"insert":" baz"}]}}}, "op2":{"type":"Edit", "location":[{"field":{"name":"name", "number":1}}], "delta":{"quill":{"ops":[{"retain":"4"}, {"insert":"qux "}, {"retain":"3"}]}}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"foo bar"}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"foo qux bar baz"}}
{"name":"move_then_edit_0_to_0", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"0"}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "b", "c", "d"]}}
{"name":"move_then_edit_0_to_1", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"1"}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "b", "c", "d"]}}
{"name":"move_then_edit_0_to_2", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"2"}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "x", "c", "d"]}}
{"name":"move_then_edit_0_to_3", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"3"}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "c", "x", "d"]}}
{"name":"move_then_edit_0_to_4", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"4"}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "c", "d", "x"]}}
{"name":"move_then_edit_3_to_0", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "index":"0"}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "a", "b", "c"]}}
{"name":"move_then_edit_3_to_1", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "index":"1"}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "x", "b", "c"]}}
{"name":"move_then_edit_3_to_2", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "index":"2"}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "x", "c"]}}
{"name":"move_then_edit_3_to_3", "op1":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "index":"3"}, "op2":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "x"]}}
{"name":"identical_map_inserts", "op1":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"a"}}, "op2":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"b"}}, "data":{"@type":"type.googleapis.com/tests.Company"}, "expected1":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a"}}, "expected2":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"b"}}}
{"name":"insert_delete", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}]}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x"]}}
{"name":"identical_list_inserts", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Person"}, "expected1":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "y"]}, "expected2":{"@type":"type.googleapis.com/tests.Person", "alias":["y", "x"]}}
{"name":"double_inserts", "op1":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"y"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "a", "y", "b"]}}
{"name":"independent_inserts", "op1":{"type":"Set", "location":[{"field":{"name":"company", "number":5}}, {"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"a"}}, "op2":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"b"}}, "data":{"@type":"type.googleapis.com/tests.Person"}, "expected":{"@type":"type.googleapis.com/tests.Person", "company":{"flags":{"1":"a"}}, "alias":["b"]}}''';
