name: protod
description: Protocol Buffer Deltas

version: 0.0.3

homepage: "https://github.com/dave/protod"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  protobuf: ^1.0.1
  fixnum: ^0.10.11

dev_dependencies:
  test: ^1.14.3