import 'dart:convert';
import 'dart:io';

import 'package:pdelta/pdelta/pdelta.dart';
import 'package:pdelta/pdelta/pdelta.pb.dart' as pb;
import 'package:pdelta/pdelta/pdelta_reduce.dart';
import 'package:pdelta_tests/pdelta_tests/pdelta_tests.op.dart';
import 'package:pdelta_tests/pdelta_tests/tests.pb.dart';
import 'package:test/test.dart' hide isNull;

import 'helpers.dart';

// Compares the structural output of the Dart reduce against the pinned Go reduce outputs (generated by
// TestReduceOutputs in reduce_outputs_test.go) for every case in the reduce corpora. This guarantees the Go and
// Dart implementations produce identical operations, not just equivalent ones.

// canonicalize sorts map keys recursively (proto map entries are unordered) but preserves list order (op order
// and list values are meaningful).
Object canonicalize(Object o) {
  if (o is Map) {
    final keys = o.keys.map((k) => "$k").toList()..sort();
    final out = {};
    for (final k in keys) {
      out[k] = canonicalize(o.entries.firstWhere((e) => "${e.key}" == k).value);
    }
    return out;
  } else if (o is List) {
    return o.map(canonicalize).toList();
  }
  return o;
}

void main() {
  init();
  for (final name in ["cases_reduce_manual", "cases_reduce_random", "cases_multi_reduce_manual"]) {
    test("outputs_$name", () async {
      final lines = await File(assetPath("$name.json")).readAsLines();
      final goLines = await File(assetPath("${name}_outputs.json")).readAsLines();
      for (var i = 0; i < lines.length; i++) {
        var str = lines[i];
        if (str.startsWith("[")) str = str.substring(1);
        if (str.endsWith("]")) str = str.substring(0, str.length - 1);
        if (str.endsWith(",")) str = str.substring(0, str.length - 1);
        var info = ReduceTestCase();
        info.mergeFromProto3Json(jsonDecode(str), typeRegistry: typeRegistry);
        final dartReduced = reduce(info.op);
        final goLine = goLines[i];
        if (goLine == "null") {
          expect(isNull(dartReduced), true, reason: "${info.name}: expected null reduction");
          continue;
        }
        final goReduced = pb.Op();
        goReduced.mergeFromProto3Json(jsonDecode(goLine), typeRegistry: typeRegistry);
        expect(
          jsonEncode(canonicalize(toObject(dartReduced))),
          jsonEncode(canonicalize(toObject(goReduced))),
          reason: info.name,
        );
      }
    });
  }
}
