// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: tests2/tests2.proto

package tests2

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// [proto:data]
type Shirt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Designer string `protobuf:"bytes,1,opt,name=designer,proto3" json:"designer,omitempty"`
	Size     uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Shirt) Reset() {
	*x = Shirt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests2_tests2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shirt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shirt) ProtoMessage() {}

func (x *Shirt) ProtoReflect() protoreflect.Message {
	mi := &file_tests2_tests2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shirt.ProtoReflect.Descriptor instead.
func (*Shirt) Descriptor() ([]byte, []int) {
	return file_tests2_tests2_proto_rawDescGZIP(), []int{0}
}

func (x *Shirt) GetDesigner() string {
	if x != nil {
		return x.Designer
	}
	return ""
}

func (x *Shirt) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_tests2_tests2_proto protoreflect.FileDescriptor

var file_tests2_tests2_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x65, 0x73, 0x74, 0x73, 0x32, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x32, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x65, 0x73, 0x74, 0x73, 0x32, 0x22, 0x37, 0x0a,
	0x05, 0x53, 0x68, 0x69, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x76, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64,
	0x2f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x32, 0x3b, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tests2_tests2_proto_rawDescOnce sync.Once
	file_tests2_tests2_proto_rawDescData = file_tests2_tests2_proto_rawDesc
)

func file_tests2_tests2_proto_rawDescGZIP() []byte {
	file_tests2_tests2_proto_rawDescOnce.Do(func() {
		file_tests2_tests2_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests2_tests2_proto_rawDescData)
	})
	return file_tests2_tests2_proto_rawDescData
}

var file_tests2_tests2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests2_tests2_proto_goTypes = []interface{}{
	(*Shirt)(nil), // 0: tests2.Shirt
}
var file_tests2_tests2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests2_tests2_proto_init() }
func file_tests2_tests2_proto_init() {
	if File_tests2_tests2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tests2_tests2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shirt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests2_tests2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests2_tests2_proto_goTypes,
		DependencyIndexes: file_tests2_tests2_proto_depIdxs,
		MessageInfos:      file_tests2_tests2_proto_msgTypes,
	}.Build()
	File_tests2_tests2_proto = out.File
	file_tests2_tests2_proto_rawDesc = nil
	file_tests2_tests2_proto_goTypes = nil
	file_tests2_tests2_proto_depIdxs = nil
}
