name: pdelta_tests_clothes
description: Protobuf package to test cross package functions.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  protobuf: ^1.0.1
  fixnum: ^0.10.11
  pdelta:
    path: ../pdelta