package tests

const applyCases = `{"name":"list_enum_set", "op":{"type":"Set", "location":[{"field":{"name":"typeList", "number":8}}], "object":{"list":{"list":[{"scalar":{"enum":3}}, {"scalar":{"enum":1}}]}}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a"}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"a", "typeList":["Charlie", "Alpha"]}}
{"name":"map_enum_set", "op":{"type":"Set", "location":[{"field":{"name":"typeMap", "number":9}}], "object":{"mapString":{"map":{"b":{"scalar":{"enum":3}}}}}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a"}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"a", "typeMap":{"b":"Charlie"}}}
{"name":"key_missing_map_value", "op":{"type":"Set", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"b"}}, {"field":{"name":"name", "number":21}}], "scalar":{"string":"c"}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a"}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"a", "cases":{"b":{"name":"c"}}}}
{"name":"insert_out_of_range", "op":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"10"}], "scalar":{"string":"b"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}}
{"name":"oneof_delete_choice", "op":{"type":"Delete", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}]}, "data":{"@type":"type.googleapis.com/tests.Chooser", "itm":{"flags":["a"]}}, "expected":{"@type":"type.googleapis.com/tests.Chooser"}}
{"name":"oneof_delete_itm", "op":{"type":"Delete", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"itm", "number":3}}]}, "data":{"@type":"type.googleapis.com/tests.Chooser", "itm":{"flags":["a"]}}, "expected":{"@type":"type.googleapis.com/tests.Chooser"}}
{"name":"oneof_delete_flags", "op":{"type":"Delete", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"itm", "number":3}}, {"field":{"name":"flags", "number":35}}]}, "data":{"@type":"type.googleapis.com/tests.Chooser", "itm":{"flags":["a"]}}, "expected":{"@type":"type.googleapis.com/tests.Chooser", "itm":{}}}
{"name":"oneof_set_inner", "op":{"type":"Insert", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"itm", "number":3}}, {"field":{"name":"flags", "number":35}}, {"index":"0"}], "scalar":{"string":"a"}}, "data":{"@type":"type.googleapis.com/tests.Chooser", "dbl":1.1}, "expected":{"@type":"type.googleapis.com/tests.Chooser", "itm":{"flags":["a"]}}}
{"name":"oneof_edit", "op":{"type":"Edit", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"str", "number":1}}], "delta":{"quill":{"ops":[{"insert":"a"}]}}}, "data":{"@type":"type.googleapis.com/tests.Chooser", "dbl":1.1}, "expected":{"@type":"type.googleapis.com/tests.Chooser", "str":"a"}}
{"name":"oneof_set_overwrite", "op":{"type":"Set", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"dbl", "number":2}}], "scalar":{"double":1.1}}, "data":{"@type":"type.googleapis.com/tests.Chooser", "str":"a"}, "expected":{"@type":"type.googleapis.com/tests.Chooser", "dbl":1.1}}
{"name":"oneof_set_dbl", "op":{"type":"Set", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"dbl", "number":2}}], "scalar":{"double":2}}, "data":{"@type":"type.googleapis.com/tests.Chooser"}, "expected":{"@type":"type.googleapis.com/tests.Chooser", "dbl":2}}
{"name":"oneof_set_str", "op":{"type":"Set", "location":[{"oneof":{"name":"choice", "fields":[{"name":"str", "number":1}, {"name":"dbl", "number":2}, {"name":"itm", "number":3}]}}, {"field":{"name":"str", "number":1}}], "scalar":{"string":"a"}}, "data":{"@type":"type.googleapis.com/tests.Chooser"}, "expected":{"@type":"type.googleapis.com/tests.Chooser", "str":"a"}}
{"name":"replace_message_with_enum", "op":{"type":"Set", "location":[{"field":{"name":"ceo", "number":14}}], "message":{"@type":"type.googleapis.com/tests.Person", "name":"a", "typeList":["Bravo"]}}, "data":{"@type":"type.googleapis.com/tests.Company", "name":"a"}, "expected":{"@type":"type.googleapis.com/tests.Company", "name":"a", "ceo":{"name":"a", "typeList":["Bravo"]}}}
{"name":"insert_map_enum", "op":{"type":"Set", "location":[{"field":{"name":"typeMap", "number":9}}, {"key":{"string":"b"}}], "scalar":{"enum":3}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a", "typeMap":{"a":"Alpha", "b":"Bravo"}}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"a", "typeMap":{"a":"Alpha", "b":"Charlie"}}}
{"name":"insert_list_enum", "op":{"type":"Insert", "location":[{"field":{"name":"typeList", "number":8}}, {"index":"0"}], "scalar":{"enum":2}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a"}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"a", "typeList":["Bravo"]}}
{"name":"replace_enum", "op":{"type":"Set", "location":[{"field":{"name":"type", "number":7}}], "scalar":{"enum":1}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a"}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"a", "type":"Alpha"}}
{"name":"delete_root", "op":{"type":"Delete"}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a"}, "expected":{"@type":"type.googleapis.com/tests.Person"}}
{"name":"replace_root", "op":{"type":"Set", "message":{"@type":"type.googleapis.com/tests.Person", "name":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"a"}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"x"}}
{"name":"empty_list", "op":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"b"}}, "data":{"@type":"type.googleapis.com/tests.Person"}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b"]}}
{"name":"nil_list", "op":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"b"}}, "data":{"@type":"type.googleapis.com/tests.Person"}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b"]}}
{"name":"empty_map", "op":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"a"}}, "data":{"@type":"type.googleapis.com/tests.Company"}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a"}}}
{"name":"nil_map", "op":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"1"}}], "scalar":{"string":"a"}}, "data":{"@type":"type.googleapis.com/tests.Company"}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a"}}}
{"name":"insert_list_scalar_0", "op":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "a", "b", "c", "d"]}}
{"name":"insert_list_scalar_1", "op":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "x", "b", "c", "d"]}}
{"name":"insert_list_scalar_2", "op":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "x", "c", "d"]}}
{"name":"insert_list_scalar_3", "op":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "x", "d"]}}
{"name":"insert_list_scalar_4", "op":{"type":"Insert", "location":[{"field":{"name":"alias", "number":6}}, {"index":"4"}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "x"]}}
{"name":"insert_list_message", "op":{"type":"Insert", "location":[{"field":{"name":"items", "number":22}}, {"index":"0"}], "message":{"@type":"type.googleapis.com/tests.Item", "title":"x"}}, "data":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"a"}, {"title":"b"}]}, "expected":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"x"}, {"title":"a"}, {"title":"b"}]}}
{"name":"insert_map_scalar", "op":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"10"}}], "scalar":{"string":"x"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b", "10":"x"}}}
{"name":"insert_map_message", "op":{"type":"Set", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"x"}}], "message":{"@type":"type.googleapis.com/tests.Case", "name":"x"}}, "data":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"a"}, "b":{"name":"b"}}}, "expected":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"a"}, "b":{"name":"b"}, "x":{"name":"x"}}}}
{"name":"delete_scalar", "op":{"type":"Delete", "location":[{"field":{"name":"name", "number":1}}]}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"foo"}, "expected":{"@type":"type.googleapis.com/tests.Person"}}
{"name":"delete_field_scalar", "op":{"type":"Delete", "location":[{"field":{"name":"company", "number":5}}, {"field":{"name":"name", "number":11}}]}, "data":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"foo"}}, "expected":{"@type":"type.googleapis.com/tests.Person", "company":{}}}
{"name":"delete_message", "op":{"type":"Delete", "location":[{"field":{"name":"company", "number":5}}]}, "data":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"foo"}}, "expected":{"@type":"type.googleapis.com/tests.Person"}}
{"name":"delete_list_scalar_start", "op":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}]}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "c", "d"]}}
{"name":"delete_list_scalar_mid", "op":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}]}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "d"]}}
{"name":"delete_list_scalar_end", "op":{"type":"Delete", "location":[{"field":{"name":"alias", "number":6}}, {"index":"3"}]}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c"]}}
{"name":"delete_list_message", "op":{"type":"Delete", "location":[{"field":{"name":"items", "number":22}}, {"index":"0"}]}, "data":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"a"}, {"title":"b"}, {"title":"c"}]}, "expected":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"b"}, {"title":"c"}]}}
{"name":"delete_map_scalar", "op":{"type":"Delete", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}]}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b", "3":"c"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "3":"c"}}}
{"name":"move_list_scalar_start_next", "op":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"2"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "a", "c", "d", "e"]}}
{"name":"move_list_scalar_start_mid", "op":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"3"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "c", "a", "d", "e"]}}
{"name":"move_list_scalar_start_end", "op":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"0"}], "index":"5"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["b", "c", "d", "e", "a"]}}
{"name":"move_list_scalar_mid_next", "op":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "index":"4"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "d", "c", "e"]}}
{"name":"move_list_scalar_mid_prev", "op":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "index":"1"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "c", "b", "d", "e"]}}
{"name":"move_list_scalar_mid_end", "op":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "index":"5"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "d", "e", "c"]}}
{"name":"move_list_scalar_mid_start", "op":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"2"}], "index":"0"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["c", "a", "b", "d", "e"]}}
{"name":"move_list_scalar_end_prev", "op":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"4"}], "index":"3"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "e", "d"]}}
{"name":"move_list_scalar_end_mid", "op":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"4"}], "index":"2"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "e", "c", "d"]}}
{"name":"move_list_scalar_end_start", "op":{"type":"Move", "location":[{"field":{"name":"alias", "number":6}}, {"index":"4"}], "index":"0"}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b", "c", "d", "e"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["e", "a", "b", "c", "d"]}}
{"name":"move_list_message", "op":{"type":"Move", "location":[{"field":{"name":"items", "number":22}}, {"index":"0"}], "index":"3"}, "data":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"a"}, {"title":"b"}, {"title":"c"}]}, "expected":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"b"}, {"title":"c"}, {"title":"a"}]}}
{"name":"move_map_scalar", "op":{"type":"Rename", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "key":{"int64":"5"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "5":"b"}}}
{"name":"move_map_message", "op":{"type":"Rename", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"b"}}], "key":{"string":"c"}}, "data":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"a"}, "b":{"name":"b"}}}, "expected":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"a"}, "c":{"name":"b"}}}}
{"name":"replace_scalar", "op":{"type":"Set", "location":[{"field":{"name":"name", "number":1}}], "scalar":{"string":"john"}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"dave"}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"john"}}
{"name":"replace_field_scalar", "op":{"type":"Set", "location":[{"field":{"name":"company", "number":5}}, {"field":{"name":"name", "number":11}}], "scalar":{"string":"apple"}}, "data":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"google"}}, "expected":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"apple"}}}
{"name":"replace_field", "op":{"type":"Set", "location":[{"field":{"name":"company", "number":5}}], "message":{"@type":"type.googleapis.com/tests.Company", "name":"apple"}}, "data":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"google"}}, "expected":{"@type":"type.googleapis.com/tests.Person", "company":{"name":"apple"}}}
{"name":"replace_index_scalar", "op":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}, {"index":"1"}], "scalar":{"string":"alex"}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["jim", "bob", "dave"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["jim", "alex", "dave"]}}
{"name":"replace_index_field", "op":{"type":"Set", "location":[{"field":{"name":"items", "number":22}}, {"index":"1"}], "message":{"@type":"type.googleapis.com/tests.Item", "title":"baz"}}, "data":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"foo"}, {"title":"bar"}]}, "expected":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"foo"}, {"title":"baz"}]}}
{"name":"replace_index_field_scalar", "op":{"type":"Set", "location":[{"field":{"name":"items", "number":22}}, {"index":"0"}, {"field":{"name":"title", "number":31}}], "scalar":{"string":"baz"}}, "data":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"foo"}, {"title":"bar"}]}, "expected":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"baz"}, {"title":"bar"}]}}
{"name":"replace_map_scalar", "op":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}, {"key":{"int64":"2"}}], "scalar":{"string":"qux"}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"foo", "2":"bar", "3":"baz"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"foo", "2":"qux", "3":"baz"}}}
{"name":"replace_map_field", "op":{"type":"Set", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"c"}}], "message":{"@type":"type.googleapis.com/tests.Case", "name":"foo"}}, "data":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"caseA"}, "b":{"name":"caseB"}, "c":{"name":"caseC"}}}, "expected":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"caseA"}, "b":{"name":"caseB"}, "c":{"name":"foo"}}}}
{"name":"replace_map_field_scalar", "op":{"type":"Set", "location":[{"field":{"name":"cases", "number":4}}, {"key":{"string":"a"}}, {"field":{"name":"name", "number":21}}], "scalar":{"string":"foo"}}, "data":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"caseA"}, "b":{"name":"caseB"}}}, "expected":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"foo"}, "b":{"name":"caseB"}}}}
{"name":"replace_replace_list_scalar", "op":{"type":"Set", "location":[{"field":{"name":"alias", "number":6}}], "object":{"list":{"list":[{"scalar":{"string":"x"}}, {"scalar":{"string":"y"}}]}}}, "data":{"@type":"type.googleapis.com/tests.Person", "alias":["a", "b"]}, "expected":{"@type":"type.googleapis.com/tests.Person", "alias":["x", "y"]}}
{"name":"replace_replace_list_message", "op":{"type":"Set", "location":[{"field":{"name":"items", "number":22}}], "object":{"list":{"list":[{"message":{"@type":"type.googleapis.com/tests.Item", "title":"x"}}, {"message":{"@type":"type.googleapis.com/tests.Item", "title":"y"}}, {"message":{"@type":"type.googleapis.com/tests.Item", "title":"z"}}]}}}, "data":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"a"}, {"title":"b"}]}, "expected":{"@type":"type.googleapis.com/tests.Case", "items":[{"title":"x"}, {"title":"y"}, {"title":"z"}]}}
{"name":"replace_replace_map_message", "op":{"type":"Set", "location":[{"field":{"name":"cases", "number":4}}], "object":{"mapString":{"map":{"x":{"message":{"@type":"type.googleapis.com/tests.Case", "name":"x"}}, "y":{"message":{"@type":"type.googleapis.com/tests.Case", "name":"y"}}, "z":{"message":{"@type":"type.googleapis.com/tests.Case", "name":"z"}}}}}}, "data":{"@type":"type.googleapis.com/tests.Person", "cases":{"a":{"name":"a"}, "b":{"name":"b"}}}, "expected":{"@type":"type.googleapis.com/tests.Person", "cases":{"x":{"name":"x"}, "y":{"name":"y"}, "z":{"name":"z"}}}}
{"name":"replace_replace_map_scalar", "op":{"type":"Set", "location":[{"field":{"name":"flags", "number":13}}], "object":{"mapInt64":{"map":{"10":{"scalar":{"string":"x"}}, "11":{"scalar":{"string":"y"}}}}}}, "data":{"@type":"type.googleapis.com/tests.Company", "flags":{"1":"a", "2":"b"}}, "expected":{"@type":"type.googleapis.com/tests.Company", "flags":{"10":"x", "11":"y"}}}
{"name":"edit_lorem_ipsum", "op":{"type":"Edit", "location":[{"field":{"name":"name", "number":1}}], "delta":{"quill":{"ops":[{"retain":"6"}, {"delete":"11"}, {"insert":"dolor sit amet"}, {"retain":"1"}]}}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"Lorem ipsum dolor."}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"Lorem dolor sit amet."}}
{"name":"edit_quick_brown_fox", "op":{"type":"Edit", "location":[{"field":{"name":"name", "number":1}}], "delta":{"quill":{"ops":[{"retain":"10"}, {"delete":"5"}, {"insert":"orange"}, {"retain":"17"}, {"delete":"12"}, {"insert":"me"}, {"retain":"1"}]}}}, "data":{"@type":"type.googleapis.com/tests.Person", "name":"the quick brown fox jumped over the lazy dog."}, "expected":{"@type":"type.googleapis.com/tests.Person", "name":"the quick orange fox jumped over me."}}`
