// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: pserver/data.proto

package pserver

import (
	delta "github.com/dave/protod/delta"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pserver_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_pserver_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_pserver_data_proto_rawDescGZIP(), []int{0}
}

// Snapshot is a lazy snapshot of the state of the document at some point in the recent past. It
// is NOT updated on every state change. To get the document in it's latest state, all future
// operations must be applied to this value.
type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int64 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"` // state of this document
	Value *Blob `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`  // marshaled protobuf
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pserver_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pserver_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_pserver_data_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Snapshot) GetValue() *Blob {
	if x != nil {
		return x.Value
	}
	return nil
}

// State is a single state change that increments the state counter by one.
type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int64 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"` // state of this document after the this op
	Op    *Blob `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`        // the operation that was applied to change the state from (state-1)->state
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pserver_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_pserver_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_pserver_data_proto_rawDescGZIP(), []int{2}
}

func (x *State) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *State) GetOp() *Blob {
	if x != nil {
		return x.Op
	}
	return nil
}

type Blob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // binary value
}

func (x *Blob) Reset() {
	*x = Blob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pserver_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_pserver_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_pserver_data_proto_rawDescGZIP(), []int{3}
}

func (x *Blob) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Payload_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // state id
	Document string    `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"` // document id
	State    int64     `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`      // state of the document that this op is acting on
	Op       *delta.Op `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`             // operation
}

func (x *Payload_Request) Reset() {
	*x = Payload_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pserver_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_Request) ProtoMessage() {}

func (x *Payload_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pserver_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_Request.ProtoReflect.Descriptor instead.
func (*Payload_Request) Descriptor() ([]byte, []int) {
	return file_pserver_data_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Payload_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payload_Request) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *Payload_Request) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Payload_Request) GetOp() *delta.Op {
	if x != nil {
		return x.Op
	}
	return nil
}

type Payload_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int64     `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"` // state of the document after the op from the client and the response op have been applied
	Op    *delta.Op `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`        // response op that must be applied to the document in order to get to the server state
}

func (x *Payload_Response) Reset() {
	*x = Payload_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pserver_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload_Response) ProtoMessage() {}

func (x *Payload_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pserver_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload_Response.ProtoReflect.Descriptor instead.
func (*Payload_Response) Descriptor() ([]byte, []int) {
	return file_pserver_data_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Payload_Response) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Payload_Response) GetOp() *delta.Op {
	if x != nil {
		return x.Op
	}
	return nil
}

var File_pserver_data_proto protoreflect.FileDescriptor

var file_pserver_data_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x11, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x2f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xae, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x66, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x02, 0x6f, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x2e, 0x4f, 0x70,
	0x52, 0x02, 0x6f, 0x70, 0x1a, 0x3b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f,
	0x70, 0x22, 0x45, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x42, 0x6c, 0x6f,
	0x62, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3c, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x42, 0x6c,
	0x6f, 0x62, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x1c, 0x0a, 0x04, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x76, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x2f, 0x70,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x3b, 0x70, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pserver_data_proto_rawDescOnce sync.Once
	file_pserver_data_proto_rawDescData = file_pserver_data_proto_rawDesc
)

func file_pserver_data_proto_rawDescGZIP() []byte {
	file_pserver_data_proto_rawDescOnce.Do(func() {
		file_pserver_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_pserver_data_proto_rawDescData)
	})
	return file_pserver_data_proto_rawDescData
}

var file_pserver_data_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pserver_data_proto_goTypes = []interface{}{
	(*Payload)(nil),          // 0: pserver.Payload
	(*Snapshot)(nil),         // 1: pserver.Snapshot
	(*State)(nil),            // 2: pserver.State
	(*Blob)(nil),             // 3: pserver.Blob
	(*Payload_Request)(nil),  // 4: pserver.Payload.Request
	(*Payload_Response)(nil), // 5: pserver.Payload.Response
	(*delta.Op)(nil),         // 6: delta.Op
}
var file_pserver_data_proto_depIdxs = []int32{
	3, // 0: pserver.Snapshot.value:type_name -> pserver.Blob
	3, // 1: pserver.State.op:type_name -> pserver.Blob
	6, // 2: pserver.Payload.Request.op:type_name -> delta.Op
	6, // 3: pserver.Payload.Response.op:type_name -> delta.Op
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pserver_data_proto_init() }
func file_pserver_data_proto_init() {
	if File_pserver_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pserver_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pserver_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pserver_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pserver_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pserver_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pserver_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pserver_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pserver_data_proto_goTypes,
		DependencyIndexes: file_pserver_data_proto_depIdxs,
		MessageInfos:      file_pserver_data_proto_msgTypes,
	}.Build()
	File_pserver_data_proto = out.File
	file_pserver_data_proto_rawDesc = nil
	file_pserver_data_proto_goTypes = nil
	file_pserver_data_proto_depIdxs = nil
}
