// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: pstore_tests/messages.proto

package pstore_tests

import (
	pdelta "github.com/dave/protod/packages/pdelta/pkg/pdelta"
	pdelta_tests "github.com/dave/protod/packages/pdelta_tests/pkg/pdelta_tests"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstore_tests_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_pstore_tests_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_pstore_tests_messages_proto_rawDescGZIP(), []int{0}
}

type Person_Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Person_Get) Reset() {
	*x = Person_Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstore_tests_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Get) ProtoMessage() {}

func (x *Person_Get) ProtoReflect() protoreflect.Message {
	mi := &file_pstore_tests_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Get.ProtoReflect.Descriptor instead.
func (*Person_Get) Descriptor() ([]byte, []int) {
	return file_pstore_tests_messages_proto_rawDescGZIP(), []int{0, 0}
}

type Person_Edit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Person_Edit) Reset() {
	*x = Person_Edit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstore_tests_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Edit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Edit) ProtoMessage() {}

func (x *Person_Edit) ProtoReflect() protoreflect.Message {
	mi := &file_pstore_tests_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Edit.ProtoReflect.Descriptor instead.
func (*Person_Edit) Descriptor() ([]byte, []int) {
	return file_pstore_tests_messages_proto_rawDescGZIP(), []int{0, 1}
}

type Person_Refresh struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Person_Refresh) Reset() {
	*x = Person_Refresh{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstore_tests_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Refresh) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Refresh) ProtoMessage() {}

func (x *Person_Refresh) ProtoReflect() protoreflect.Message {
	mi := &file_pstore_tests_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Refresh.ProtoReflect.Descriptor instead.
func (*Person_Refresh) Descriptor() ([]byte, []int) {
	return file_pstore_tests_messages_proto_rawDescGZIP(), []int{0, 2}
}

type Person_Get_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId string `protobuf:"bytes,1,opt,name=documentId,proto3" json:"documentId,omitempty"`
}

func (x *Person_Get_Request) Reset() {
	*x = Person_Get_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstore_tests_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Get_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Get_Request) ProtoMessage() {}

func (x *Person_Get_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pstore_tests_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Get_Request.ProtoReflect.Descriptor instead.
func (*Person_Get_Request) Descriptor() ([]byte, []int) {
	return file_pstore_tests_messages_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Person_Get_Request) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type Person_Get_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State  int64                `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
	Person *pdelta_tests.Person `protobuf:"bytes,3,opt,name=person,proto3" json:"person,omitempty"`
	Err    string               `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Person_Get_Response) Reset() {
	*x = Person_Get_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstore_tests_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Get_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Get_Response) ProtoMessage() {}

func (x *Person_Get_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pstore_tests_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Get_Response.ProtoReflect.Descriptor instead.
func (*Person_Get_Response) Descriptor() ([]byte, []int) {
	return file_pstore_tests_messages_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Person_Get_Response) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Person_Get_Response) GetPerson() *pdelta_tests.Person {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *Person_Get_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Person_Edit_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateId    string     `protobuf:"bytes,1,opt,name=stateId,proto3" json:"stateId,omitempty"`       // state id
	DocumentId string     `protobuf:"bytes,2,opt,name=documentId,proto3" json:"documentId,omitempty"` // document id
	State      int64      `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`          // state of the document that this op is acting on
	Op         *pdelta.Op `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`                 // operation
}

func (x *Person_Edit_Request) Reset() {
	*x = Person_Edit_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstore_tests_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Edit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Edit_Request) ProtoMessage() {}

func (x *Person_Edit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pstore_tests_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Edit_Request.ProtoReflect.Descriptor instead.
func (*Person_Edit_Request) Descriptor() ([]byte, []int) {
	return file_pstore_tests_messages_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Person_Edit_Request) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *Person_Edit_Request) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Person_Edit_Request) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Person_Edit_Request) GetOp() *pdelta.Op {
	if x != nil {
		return x.Op
	}
	return nil
}

type Person_Edit_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State int64      `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"` // state of the document after the op from the client and the response op have been applied
	Op    *pdelta.Op `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`        // response op that must be applied to the document in order to get to the server state
	Err   string     `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Person_Edit_Response) Reset() {
	*x = Person_Edit_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstore_tests_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Edit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Edit_Response) ProtoMessage() {}

func (x *Person_Edit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pstore_tests_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Edit_Response.ProtoReflect.Descriptor instead.
func (*Person_Edit_Response) Descriptor() ([]byte, []int) {
	return file_pstore_tests_messages_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Person_Edit_Response) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Person_Edit_Response) GetOp() *pdelta.Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Person_Edit_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Person_Refresh_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DocumentId string `protobuf:"bytes,1,opt,name=documentId,proto3" json:"documentId,omitempty"` // document id
}

func (x *Person_Refresh_Request) Reset() {
	*x = Person_Refresh_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstore_tests_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Refresh_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Refresh_Request) ProtoMessage() {}

func (x *Person_Refresh_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pstore_tests_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Refresh_Request.ProtoReflect.Descriptor instead.
func (*Person_Refresh_Request) Descriptor() ([]byte, []int) {
	return file_pstore_tests_messages_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Person_Refresh_Request) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type Person_Refresh_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Person_Refresh_Response) Reset() {
	*x = Person_Refresh_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pstore_tests_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Refresh_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Refresh_Response) ProtoMessage() {}

func (x *Person_Refresh_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pstore_tests_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Refresh_Response.ProtoReflect.Descriptor instead.
func (*Person_Refresh_Response) Descriptor() ([]byte, []int) {
	return file_pstore_tests_messages_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Person_Refresh_Response) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_pstore_tests_messages_proto protoreflect.FileDescriptor

var file_pstore_tests_messages_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x18, 0x70, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x70, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x2f, 0x70, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x03, 0x0a, 0x06, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x1a, 0x92, 0x01, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x1a, 0x29, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x60, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x52, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a, 0xcd, 0x01, 0x0a, 0x04, 0x45,
	0x64, 0x69, 0x74, 0x1a, 0x75, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a,
	0x0a, 0x02, 0x6f, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x1a, 0x4e, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x02,
	0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x64, 0x65, 0x6c, 0x74,
	0x61, 0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x1a, 0x52, 0x0a, 0x07, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x1a, 0x29, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x1a, 0x1c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x42, 0x4c,
	0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x76,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x73, 0x2f, 0x70, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x3b,
	0x70, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pstore_tests_messages_proto_rawDescOnce sync.Once
	file_pstore_tests_messages_proto_rawDescData = file_pstore_tests_messages_proto_rawDesc
)

func file_pstore_tests_messages_proto_rawDescGZIP() []byte {
	file_pstore_tests_messages_proto_rawDescOnce.Do(func() {
		file_pstore_tests_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_pstore_tests_messages_proto_rawDescData)
	})
	return file_pstore_tests_messages_proto_rawDescData
}

var file_pstore_tests_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pstore_tests_messages_proto_goTypes = []interface{}{
	(*Person)(nil),                  // 0: pstore_tests.Person
	(*Person_Get)(nil),              // 1: pstore_tests.Person.Get
	(*Person_Edit)(nil),             // 2: pstore_tests.Person.Edit
	(*Person_Refresh)(nil),          // 3: pstore_tests.Person.Refresh
	(*Person_Get_Request)(nil),      // 4: pstore_tests.Person.Get.Request
	(*Person_Get_Response)(nil),     // 5: pstore_tests.Person.Get.Response
	(*Person_Edit_Request)(nil),     // 6: pstore_tests.Person.Edit.Request
	(*Person_Edit_Response)(nil),    // 7: pstore_tests.Person.Edit.Response
	(*Person_Refresh_Request)(nil),  // 8: pstore_tests.Person.Refresh.Request
	(*Person_Refresh_Response)(nil), // 9: pstore_tests.Person.Refresh.Response
	(*pdelta_tests.Person)(nil),     // 10: pdelta_tests.Person
	(*pdelta.Op)(nil),               // 11: pdelta.Op
}
var file_pstore_tests_messages_proto_depIdxs = []int32{
	10, // 0: pstore_tests.Person.Get.Response.person:type_name -> pdelta_tests.Person
	11, // 1: pstore_tests.Person.Edit.Request.op:type_name -> pdelta.Op
	11, // 2: pstore_tests.Person.Edit.Response.op:type_name -> pdelta.Op
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pstore_tests_messages_proto_init() }
func file_pstore_tests_messages_proto_init() {
	if File_pstore_tests_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pstore_tests_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pstore_tests_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pstore_tests_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Edit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pstore_tests_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Refresh); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pstore_tests_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Get_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pstore_tests_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Get_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pstore_tests_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Edit_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pstore_tests_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Edit_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pstore_tests_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Refresh_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pstore_tests_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Refresh_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pstore_tests_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pstore_tests_messages_proto_goTypes,
		DependencyIndexes: file_pstore_tests_messages_proto_depIdxs,
		MessageInfos:      file_pstore_tests_messages_proto_msgTypes,
	}.Build()
	File_pstore_tests_messages_proto = out.File
	file_pstore_tests_messages_proto_rawDesc = nil
	file_pstore_tests_messages_proto_goTypes = nil
	file_pstore_tests_messages_proto_depIdxs = nil
}
